name: Build
on:
  push:
    branches:
    - main
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        sudo apt-get install g++ cmake -y
        cmake .
        make
    - uses: actions/upload-artifact@v3
      with:
        name: cbook-linux-amd64
        path: bin/cbook

